
unit uKSObjects;

interface

const

	// bank 0:
	KSOBJ_SAVEPOINT = 1;
	KSOBJ_WIN       = 2;

	KSOBJ_PU_RUN       = 3;
	KSOBJ_PU_WALLCLIMB = 4;
	KSOBJ_PU_DBLJUMP   = 5;
	KSOBJ_PU_HIGHJUMP  = 6;
	KSOBJ_PU_EYE       = 7;
	KSOBJ_PU_DETECTOR  = 8;
	KSOBJ_PU_UMBRELLA  = 9;
	KSOBJ_PU_HOLOGRAM  = 10;

	KSOBJ_NOCLIMB  = 11;
	
	KSOBJ_EYEMUSIC = 12;
	KSOBJ_STICKY   = 13;
	KSOBJ_SHIFTA   = 14;
	KSOBJ_SHIFTB   = 15;
	KSOBJ_SHIFTC   = 16;
	KSOBJ_SIGNA    = 17;
	KSOBJ_SIGNB    = 18;
	KSOBJ_SIGNC    = 19;
	KSOBJ_WARP     = 20;			// Warps are always relative

	KSOBJ_KEY_RED    = 21;
	KSOBJ_KEY_YELLOW = 22;
	KSOBJ_KEY_BLUE   = 23;
	KSOBJ_KEY_PURPLE = 24;

	KSOBJ_NOJUMP = 25;

	KSOBJ_DETECTTARGET_RED   = 26;
	KSOBJ_DETECTTARGET_GREEN = 27;
	KSOBJ_DETECTTARGET_BLUE  = 28;

	KSOBJ_SIGNAREAA = 29;
	KSOBJ_SIGNAREAB = 30;
	KSOBJ_SIGNAREAC = 31;





	PowerupIndices: array[0..11] of integer = (
		KSOBJ_PU_RUN,
		KSOBJ_PU_WALLCLIMB,
		KSOBJ_PU_DBLJUMP,
		KSOBJ_PU_HIGHJUMP,
		KSOBJ_PU_EYE,
		KSOBJ_PU_DETECTOR,
		KSOBJ_PU_UMBRELLA,
		KSOBJ_PU_HOLOGRAM,
		KSOBJ_KEY_RED,
		KSOBJ_KEY_YELLOW,
		KSOBJ_KEY_BLUE,
		KSOBJ_KEY_PURPLE
	);




implementation





end.
 